spring:
  application:
    name: Controle Estoque

  datasource:
    url: jdbc:postgresql://localhost:5432/atelie
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:

      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true